# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  # --- Build Stage ---
 build-nginx-setup:
    name: Job 3 of Build - Setup Nginx Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Start Nginx service
        run: sudo systemctl start nginx

      - name: Check Nginx status
        run: sudo systemctl status nginx


 
